meta_product_name: "Surfinder"
meta_title: "The best way to find your Surf School"
meta_description: "Surfinder was created during batch 276 of the Boredeaux Wagon, by Letizia, Luix, James and Mickael. This is the best solution to find your Surf School"
meta_image: "cover.png"
