meta_product_name: "SURFINDEЯ"
meta_title: "SURFINDEЯ - Find the surfschool that suits you!"
meta_description: "Surfinder will help you find and book surf lessons in a surf school. We provide you school description, reviews and surf forecast."
meta_image: "cover.png"
